replicaCount: 1

image:
  repository: ghcr.io/texano00/k8s-gateway-api-playground/dummy-app
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.0.0-blue"

fullnameOverride: "dummy-v1-blue"

serviceAccount:
  create: false

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: gce
  hosts:
    - host: "my-dummy-colored-app-exposed-by-ingress.net"
      paths:
        - path: /
          pathType: ImplementationSpecific