apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: shared-public-gateway-my-dummy-colored-app
  namespace: infrastructure
spec:
  gatewayClassName: gke-l7-global-external-managed
  listeners:
  - name: http
    protocol: HTTP
    hostname: my-dummy-colored-app.net
    port: 80
    allowedRoutes:
      kinds:
      - kind: HTTPRoute
      namespaces:
        from: Selector
        selector:
          matchLabels:
            shared-gateway-access: "true"
    # tls:
    #   certificateRefs:
    #   - name: foo-example-com
